[package]
name = "LocalType"
version = "1.2.1"
description = "手机到电脑的无缝打字工具"
authors = ["VenenoSix24 <lagbqy@gmail.com>"]
edition = "2021"

[lib]
name = "localtype_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
local-ip-address = "0.5"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
rand = "0.8"
directories = "5.0"
enigo = "0.3.0"
hostname = "0.3"
arboard = "3.3"
tokio-rustls = "0.24"
rcgen = "0.11"
tauri-plugin-autostart = "2.5.1"

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols
